# Generated by Django 4.0 on 2022-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
    ]
